# Changes here will be overwritten by Copier
_commit: 0.14.2
_src_path: gh:bhklab/bhklab-project-template
additional_authors_raw: Michael Tran
author_email: bhklab.jamesbannon@gmail.com
author_full_name: James Bannon
github_username: jbannon
has_additional_authors: true
project_description: Pipeline to process the 3D structures from the GEOM database
project_name: Geom Pipeline
project_slug: geom-pipeline
publish_to_github: true
python_version: '3.12'
repo_location: bhklab
