site_name: GEOM Pipeline
repo_name: geom-pipeline
site_description: Documentation for the GEOM pipeline
site_author: Michael Tran <michaelcao-anh.tran@uhn.ca>
docs_dir: docs
site_dir: site
nav:
  - Home: README.md
  - colData: colData.md
  - MAE: mae.md
  - Developer Notes: devnotes.md
theme: readthedocs
plugins:
  - search
